import { Activity, Ban, Clock3, Globe2, Radio, ShieldX, Tv2, WifiOff } from "lucide-react"
import { getAdminOverview } from "@/lib/admin/data"
import { HealthAreaChart, HealthPie, MetricCard, PageTitle, Panel, StatusBadge } from "@/components/admin/admin-ui"

export default async function AdminOverviewPage() {
  const data = await getAdminOverview()
  const recent = data.channels.filter((channel) => channel.status !== "online").slice(0, 6)
  return <div><PageTitle title="Dashboard overview" description="Live operational status across the Global IPTV catalog." />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total channels" value={data.totals.channels.toLocaleString()} detail="Provider-published streams" icon={<Tv2 className="size-5"/>}/><MetricCard label="Online channels" value={data.totals.online.toLocaleString()} detail={`${Math.round(data.totals.online / Math.max(data.totals.channels, 1) * 100)}% availability`} tone="green" icon={<Radio className="size-5"/>}/><MetricCard label="Offline channels" value={data.totals.offline.toLocaleString()} tone="red" icon={<WifiOff className="size-5"/>}/><MetricCard label="Blocked channels" value={data.totals.blocked.toLocaleString()} tone="amber" icon={<Ban className="size-5"/>}/><MetricCard label="Removed channels" value={data.totals.removed.toLocaleString()} tone="purple" icon={<ShieldX className="size-5"/>}/><MetricCard label="Total countries" value={data.totals.countries} icon={<Globe2 className="size-5"/>}/><MetricCard label="Active countries" value={data.totals.activeCountries} tone="green" icon={<Activity className="size-5"/>}/><MetricCard label="Last stream check" value="Just now" detail={new Date(data.lastStreamCheck).toLocaleString()} tone="purple" icon={<Clock3 className="size-5"/>}/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Panel title="Availability trend" description="Online stream percentage over the last seven days"><HealthAreaChart/></Panel><Panel title="Current health distribution"><HealthPie online={data.totals.online} offline={data.totals.offline} blocked={data.totals.blocked}/></Panel></div>
    <Panel className="mt-5" title="Channels requiring attention" description="Highest-priority stream health issues"><div className="space-y-2">{recent.map((channel) => <div key={channel.id} className="flex items-center gap-3 rounded-xl bg-secondary/35 p-3"><span className="grid size-9 place-items-center rounded-lg bg-red-500/10 text-sm font-bold text-red-400">{channel.name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{channel.name}</p><p className="text-xs text-muted-foreground">{channel.country} · {channel.lastError}</p></div><StatusBadge status={channel.status}/><span className="hidden text-xs text-muted-foreground sm:block">{channel.responseTime}ms</span></div>)}</div></Panel>
  </div>
}
