import { lookup } from "node:dns/promises"
import { spawn } from "node:child_process"
import { authorizeAdminApi } from "@/lib/admin/auth"

export const runtime = "nodejs"
function privateIp(ip: string) { return /^(127\.|10\.|0\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|::1$|fc|fd|fe80)/i.test(ip) }
async function validateUrl(raw: string) { const url=new URL(raw); if(!["http:","https:"].includes(url.protocol)) throw new Error("Only HTTP(S) streams are allowed"); const addresses=await lookup(url.hostname,{all:true}); if(addresses.some(item=>privateIp(item.address))) throw new Error("Private network targets are not allowed"); return url }
function probe(url:string){return new Promise<{codec:string;resolution:string;probeError:string|null}>((resolve)=>{const path=process.env.FFPROBE_PATH;if(!path){resolve({codec:"Not configured",resolution:"Unknown",probeError:"Set FFPROBE_PATH to enable codec validation"});return}const child=spawn(path,["-v","error","-select_streams","v:0","-show_entries","stream=codec_name,width,height","-of","json",url],{windowsHide:true});let output="";let error="";const timer=setTimeout(()=>child.kill(),12000);child.stdout.on("data",chunk=>output+=chunk);child.stderr.on("data",chunk=>error+=chunk);child.on("error",event=>{clearTimeout(timer);resolve({codec:"Unavailable",resolution:"Unknown",probeError:event.message})});child.on("close",()=>{clearTimeout(timer);try{const parsed=JSON.parse(output);const stream=parsed.streams?.[0];resolve({codec:stream?.codec_name?.toUpperCase()||"Unknown",resolution:stream?.width&&stream?.height?`${stream.width}x${stream.height}`:"Unknown",probeError:error||null})}catch{resolve({codec:"Unknown",resolution:"Unknown",probeError:error||"No video stream metadata returned"})}})})}
export async function POST(request:Request){const auth=await authorizeAdminApi("moderator");if("response" in auth)return auth.response;try{const body=await request.json();const url=await validateUrl(String(body.url||""));const started=performance.now();const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);let response:Response;try{response=await fetch(url,{method:"HEAD",redirect:"error",signal:controller.signal,headers:{"User-Agent":"Global-IPTV-Admin/1.0"}})}catch{response=await fetch(url,{method:"GET",redirect:"error",signal:controller.signal,headers:{Range:"bytes=0-2047","User-Agent":"Global-IPTV-Admin/1.0"}})}finally{clearTimeout(timeout)}const latency=Math.round(performance.now()-started);const metadata=await probe(url.toString());const online=response.ok;await auth.supabase.from("stream_checks").insert({channel_id:String(body.channelId||"unknown"),status:online?"online":"offline",response_time_ms:latency,http_status:response.status,codec:metadata.codec,resolution:metadata.resolution,error_message:metadata.probeError});return Response.json({status:online?"ONLINE":"OFFLINE",latency:`${latency}ms`,httpStatus:response.status,codec:metadata.codec,resolution:metadata.resolution,ffprobe:metadata.probeError?"warning":"validated"})}catch(error){return Response.json({status:"OFFLINE",error:error instanceof Error?error.message:"Stream test failed"},{status:400})}}
