import { notFound } from "next/navigation"
import { ArrowLeft, Clock3, Globe2, Languages, Tags, Tv2 } from "lucide-react"
import Link from "next/link"
import { getAdminOverview } from "@/lib/admin/data"
import { PageTitle, Panel, StatusBadge, StreamTest } from "@/components/admin/admin-ui"
import { requireAdminPage } from "@/lib/admin/auth"

export default async function AdminChannelDetailsPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const [admin,data] = await Promise.all([requireAdminPage(),getAdminOverview()]); const channel = data.channels.find((item) => item.id === id); if (!channel) notFound(); const checks = Array.from({ length: 30 }, (_, index) => (index + channel.failures) % 11 !== 0); return <div><Link href="/admin/channels" className="mb-5 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Back to channels</Link><PageTitle title={channel.name} description="Channel metadata, stream configuration, and health history." actions={<StatusBadge status={channel.status}/>}/><div className="grid gap-5 xl:grid-cols-2"><Panel title="Channel information"><div className="grid gap-4 sm:grid-cols-2">{[["Country",channel.country,Globe2],["Category",channel.category,Tags],["Language",channel.language,Languages],["Channel ID",channel.id,Tv2]].map(([label,value,Icon]) => { const I = Icon as typeof Tv2; return <div key={String(label)} className="rounded-xl bg-secondary/40 p-4"><I className="mb-3 size-4 text-blue"/><p className="text-xs text-muted-foreground">{String(label)}</p><p className="mt-1 truncate text-sm font-semibold capitalize">{String(value)}</p></div> })}</div></Panel><Panel title="Stream information"><div className="space-y-4"><div><p className="text-xs text-muted-foreground">Current URL</p><p className="mt-1 break-all rounded-xl bg-secondary/40 p-3 font-mono text-xs">{channel.streamUrl}</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="size-4"/>Last successful check: just now</div><StreamTest channel={channel} role={admin.role}/></div></Panel></div><Panel className="mt-5" title="Health history" description="Last 30 automated checks"><div className="flex flex-wrap gap-2">{checks.map((passed,index) => <span key={index} title={`Check ${index+1}: ${passed ? "Online" : "Failed"}`} className={cnDot(passed)}/>)}</div></Panel></div> }

function cnDot(passed: boolean) { return `size-4 rounded-full ${passed ? "bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,.35)]" : "bg-red-500 shadow-[0_0_10px_rgba(239,68,68,.35)]"}` }
